"""Create F1 tables

Revision ID: 58015ba10a0a
Revises: 1622780d2161
Create Date: 2025-05-26 15:52:13.905689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58015ba10a0a'
down_revision: Union[str, None] = '1622780d2161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('points_scored', sa.Integer(), nullable=True))
    op.drop_column('drivers', 'points')
    op.add_column('teams', sa.Column('Team_principal', sa.String(length=50), nullable=False))
    op.drop_column('teams', 'principal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('principal', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('teams', 'Team_principal')
    op.add_column('drivers', sa.Column('points', sa.INTEGER(), nullable=True))
    op.drop_column('drivers', 'points_scored')
    # ### end Alembic commands ###
